class EmptyData(Exception):...
    #raise when user data is empty

class InvalidNumericData(Exception):...
    #Raise when data is not numeric

class InvalidStringData(Exception):...
    #Raise when data is not string

class SpecialCharacterError(Exception):...
    #Raise when data contains special characters

class InvalidSize(Exception):...
    #Raise when data size is invalid

class InvalidEmailAddress(Exception):...
    #Raise when Email is invalid

class InvalidToken(Exception):...
    #Raise when user token is invalid